---
title: "Ambient"
author: "Patrick Snelgar"
date: "8/06/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message= FALSE)

library(here)
library(scales)
library(magrittr)
library(tidyverse)
library(lubridate)

```
```{r cabinet-monitoring}

cabinet_data <- 
	read_csv(here("input/header house growth cabinets_growth_cabinets.dat"), skip = 1) %>%
	mutate(TMSTAMP = ymd_hms(TMSTAMP)) %>%
	filter(TMSTAMP > ymd("2021-06-14"))
# only works if the columns aren't empty

if(!any(is.na(cabinet_data[1, 10:12]))) {
	sensor_names <- 
	as.character(cabinet_data[1,10:12])
} else {
	sensor_names <- 
		as.character(cabinet_data[1,7:9])
}

names <- 
	c(names(cabinet_data[,c(1, 3)]), 
	  sensor_names)

cabinet_data <- 
	cabinet_data[,c(-2, -7:-12)]

names(cabinet_data) <- names

cabinet_data %>%
	pivot_longer(cols = 3:5, names_to = "sensor_id", values_to = "temperature") %>%
	filter(TMSTAMP > last(TMSTAMP) - 7 * 24 * 3600) %>%
	ggplot(aes(TMSTAMP, temperature, colour = sensor_id)) +
		geom_point() +
		geom_line() +
		scale_x_datetime(breaks = pretty_breaks(24)) +
		scale_y_continuous(breaks = pretty_breaks(10)) + 
		theme_bw() +
		theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

```

```{r}

met_data <- 
	read_csv(here("input/Metwatch Export.csv"))


```
